In [1]:
import numpy as np
import pandas
from tensorflow import keras
from keras.models import Sequential
from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import Dense, Activation, Dropout
from sklearn.model_selection import StratifiedKFold

Using TensorFlow backend.


In [2]:
#masukin data1
data1=pandas.read_csv('D:\\SKRIPSI\\data\\data_praproses\\jamu_herbs.csv', sep=',')
data1.values

array([['J00021', 0, 0, ..., 0, 0, 0],
       ['J00050', 0, 0, ..., 0, 0, 0],
       ['J00113', 1, 0, ..., 0, 0, 0],
       ...,
       ['J03006', 0, 0, ..., 0, 0, 0],
       ['J03017', 0, 0, ..., 0, 0, 0],
       ['J03023', 0, 0, ..., 0, 0, 0]], dtype=object)

In [3]:
#masukin data2
data2=pandas.read_csv('D:\\SKRIPSI\\data\\data_praproses\\jamu_class.csv', sep=',')
data2.values

array([['J00021', 17],
       ['J00050', 17],
       ['J00113', 17],
       ...,
       ['J03006', 16],
       ['J03017', 16],
       ['J03023', 16]], dtype=object)

In [37]:
data_1 = data1.drop('IDJamu',axis=1)
data_2 = data2.drop('Jamu ID',axis=1)

In [38]:
data_1['Kelas']=data_2['Class of Diseases']

In [40]:
data_temp  = data_1[data_1['Kelas'] != 5]
X = data_temp.drop('Kelas', axis=1).values
y = data_temp['Kelas'].values

In [7]:
from sklearn.model_selection import KFold

In [8]:
#untuk k=10
kf = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)
val_loss_cv = []
val_acc_cv = []
j = 0
for train_index, test_index in kf.split(X,y):
    j+=1
    print(f"Fold {j} :")
    print("")
    X_train,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
    model = Sequential()
    model.add(Dense(input_dim=X_train.shape[1], units=128,
                     kernel_initializer='normal', bias_initializer='zeros'))
    model.add(Activation('relu'))

    for i in range(0, 6):
        model.add(Dense(units=128, kernel_initializer='normal',
                         bias_initializer='zeros'))
        model.add(Activation('relu'))
        model.add(Dropout(.15))

    model.add(Dense(units=19))
    model.add(Activation('softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train,batch_size=24,epochs=30,verbose=1,validation_data=(X_test, y_test))
    score = model.evaluate(X_test, y_test, verbose=1)
    val_loss_cv.append(score[0])
    val_acc_cv.append(score[1])

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Fold 1 :

Train on 2704 samples, validate on 311 samples
Epoch 1/30
2704/2704 [==============================] - 4s 1ms/step - loss: 2.2961 - acc: 0.2001 - val_loss: 2.1434 - val_acc: 0.2090
Epoch 2/30
2704/2704 [==============================] - 1s 261us/step - loss: 2.0303 - acc: 0.2559 - val_loss: 2.0837 - val_acc: 0.3248
Epoch 3/30
2704/2704 [==============================] - 1s 214us/step - loss: 1.7878 - acc: 0.3561 - val_loss: 1.7224 - val_acc: 0.3859
Epoch 4/30
2704/2704 [==============================] - 1s 215us/step - loss: 1.4765 - acc: 0.4959 - val_loss: 1.6784 - val_acc: 0.4630
Epoch 5/30
2704/2704 [==============================] - 1s 247us/step - loss: 1.2569 - acc: 0.6084 - val_loss: 1.7251 - val_acc: 0.5048
Epoch 6/30
2704/2704 [==============================] - 1s 225us/step - loss: 1.1029 - acc: 0.6690 - val_loss: 1.6704 - val_acc: 0.5241
Epoch 7/30
2704/2704 [==============================] - 1s 222us/step - loss: 0.9745 - acc: 0.7027 - val_loss: 1.7959 - val_acc: 

2707/2707 [==============================] - 1s 245us/step - loss: 0.3107 - acc: 0.9106 - val_loss: 3.7416 - val_acc: 0.4188
Epoch 30/30
308/308 [==============================] - 0s 83us/step
Fold 3 :

Train on 2712 samples, validate on 303 samples
Epoch 1/30
2712/2712 [==============================] - 2s 591us/step - loss: 2.3000 - acc: 0.1903 - val_loss: 2.0742 - val_acc: 0.2145
Epoch 2/30
2712/2712 [==============================] - 1s 246us/step - loss: 2.0403 - acc: 0.2268 - val_loss: 2.0398 - val_acc: 0.1914
Epoch 3/30
2712/2712 [==============================] - 1s 260us/step - loss: 1.8104 - acc: 0.3525 - val_loss: 1.6873 - val_acc: 0.4785
Epoch 4/30
2712/2712 [==============================] - 1s 229us/step - loss: 1.5130 - acc: 0.4860 - val_loss: 1.6458 - val_acc: 0.4587
Epoch 5/30
2712/2712 [==============================] - 1s 235us/step - loss: 1.2888 - acc: 0.5914 - val_loss: 1.5156 - val_acc: 0.5545
Epoch 6/30
2712/2712 [==============================] - 1s 257us/step 

2714/2714 [==============================] - 1s 223us/step - loss: 0.3498 - acc: 0.8957 - val_loss: 2.6158 - val_acc: 0.5781
Epoch 28/30
2714/2714 [==============================] - 1s 234us/step - loss: 0.3308 - acc: 0.8998 - val_loss: 2.4455 - val_acc: 0.6013
Epoch 29/30
2714/2714 [==============================] - 1s 251us/step - loss: 0.3284 - acc: 0.9046 - val_loss: 2.5365 - val_acc: 0.5415
Epoch 30/30
301/301 [==============================] - 0s 114us/step
Fold 5 :

Train on 2714 samples, validate on 301 samples
Epoch 1/30
2714/2714 [==============================] - 2s 675us/step - loss: 2.2944 - acc: 0.2012 - val_loss: 2.0610 - val_acc: 0.2159
Epoch 2/30
2714/2714 [==============================] - 1s 269us/step - loss: 2.0335 - acc: 0.2034 - val_loss: 2.0660 - val_acc: 0.3588
Epoch 3/30
2714/2714 [==============================] - 1s 343us/step - loss: 1.8117 - acc: 0.3747 - val_loss: 1.6233 - val_acc: 0.4651
Epoch 4/30
2714/2714 [==============================] - 1s 307us/st

2714/2714 [==============================] - 1s 254us/step - loss: 0.2700 - acc: 0.9219 - val_loss: 2.7763 - val_acc: 0.5415
Epoch 26/30
2714/2714 [==============================] - 1s 233us/step - loss: 0.2851 - acc: 0.9204 - val_loss: 2.8916 - val_acc: 0.5216
Epoch 27/30
2714/2714 [==============================] - 1s 274us/step - loss: 0.2858 - acc: 0.9189 - val_loss: 2.7367 - val_acc: 0.5847
Epoch 28/30
2714/2714 [==============================] - 1s 260us/step - loss: 0.2647 - acc: 0.9267 - val_loss: 2.9285 - val_acc: 0.5548
Epoch 29/30
2714/2714 [==============================] - 1s 257us/step - loss: 0.2560 - acc: 0.9274 - val_loss: 2.8521 - val_acc: 0.5415
Epoch 30/30
301/301 [==============================] - 0s 81us/step
Fold 7 :

Train on 2715 samples, validate on 300 samples
Epoch 1/30
2715/2715 [==============================] - 2s 762us/step - loss: 2.2902 - acc: 0.2103 - val_loss: 2.1161 - val_acc: 0.2200
Epoch 2/30
2715/2715 [==============================] - 1s 243us/s

2718/2718 [==============================] - 1s 247us/step - loss: 0.3067 - acc: 0.9054 - val_loss: 2.9156 - val_acc: 0.5623
Epoch 24/30
2718/2718 [==============================] - 1s 240us/step - loss: 0.3018 - acc: 0.9128 - val_loss: 2.5564 - val_acc: 0.5960
Epoch 25/30
2718/2718 [==============================] - 1s 252us/step - loss: 0.2749 - acc: 0.9220 - val_loss: 2.7224 - val_acc: 0.6027
Epoch 26/30
2718/2718 [==============================] - 1s 251us/step - loss: 0.2610 - acc: 0.9242 - val_loss: 2.7150 - val_acc: 0.6229
Epoch 27/30
2718/2718 [==============================] - 1s 251us/step - loss: 0.2591 - acc: 0.9275 - val_loss: 2.5590 - val_acc: 0.6061
Epoch 28/30
2718/2718 [==============================] - 1s 252us/step - loss: 0.2684 - acc: 0.9202 - val_loss: 2.5695 - val_acc: 0.6061
Epoch 29/30
2718/2718 [==============================] - 1s 251us/step - loss: 0.2521 - acc: 0.9268 - val_loss: 2.6764 - val_acc: 0.6128
Epoch 30/30
297/297 [==============================] 

2719/2719 [==============================] - 1s 359us/step - loss: 0.4015 - acc: 0.8849 - val_loss: 2.1703 - val_acc: 0.5946
Epoch 22/30
2719/2719 [==============================] - 1s 283us/step - loss: 0.3649 - acc: 0.8941 - val_loss: 2.4416 - val_acc: 0.6047
Epoch 23/30
2719/2719 [==============================] - 1s 258us/step - loss: 0.3397 - acc: 0.8996 - val_loss: 2.3673 - val_acc: 0.5946
Epoch 24/30
2719/2719 [==============================] - 1s 239us/step - loss: 0.3382 - acc: 0.8974 - val_loss: 2.4169 - val_acc: 0.6047
Epoch 25/30
2719/2719 [==============================] - 1s 303us/step - loss: 0.3306 - acc: 0.9029 - val_loss: 2.5130 - val_acc: 0.6149
Epoch 26/30
2719/2719 [==============================] - 1s 263us/step - loss: 0.3146 - acc: 0.9103 - val_loss: 2.6536 - val_acc: 0.6014
Epoch 27/30
2719/2719 [==============================] - 1s 238us/step - loss: 0.3070 - acc: 0.9084 - val_loss: 2.7074 - val_acc: 0.5709
Epoch 28/30
2719/2719 [==============================

In [9]:
print(f"val_loss_cv : {val_loss_cv}")
print(f"mean_val_loss_cv : {np.mean(val_loss_cv)}")
print(f"val_acc_cv : {val_acc_cv}")
print(f"mean_val_acc_cv : {np.mean(val_acc_cv)}")

val_loss_cv : [3.7036242101736776, 3.9519291233706784, 3.1221593724619043, 2.6997571593503222, 2.5282895929393576, 2.8131870874930853, 3.027012665271759, 2.8175790000844887, 2.4955170885079636, 2.7892347993077458]
mean_val_loss_cv : 2.9948290098960983
val_acc_cv : [0.47588424384593964, 0.41558441577793714, 0.5346534655186603, 0.5548172760445415, 0.6245847187961059, 0.5581395358738314, 0.5966666666666667, 0.5892255898276564, 0.6195286197293086, 0.5878378378378378]
mean_val_acc_cv : 0.5556922369918486


In [59]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=0)
for train_index, test_index in sss.split(X,y):
    X_train,X_test = X[train_index],X[test_index]
    y_train,y_test = y[train_index],y[test_index]
    model = Sequential()
    model.add(Dense(input_dim=X_train.shape[1], units=128,
                     kernel_initializer='normal', bias_initializer='zeros'))
    model.add(Activation('relu'))

    for i in range(0, 6):
        model.add(Dense(units=128, kernel_initializer='normal',
                         bias_initializer='zeros'))
        model.add(Activation('relu'))
        model.add(Dropout(.15))

    model.add(Dense(units=19))
    model.add(Activation('softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train,batch_size=24,epochs=30,verbose=1,validation_data=(X_test, y_test))
    score = model.evaluate(X_test, y_test, verbose=1)
    val_loss_cv.append(score[0])
    val_acc_cv.append(score[1])
    predict = model.predict_classes(X_test)

Train on 2109 samples, validate on 905 samples
Epoch 1/30
2109/2109 [==============================] - 3s 1ms/step - loss: 2.3081 - acc: 0.2077 - val_loss: 2.0970 - val_acc: 0.2166
Epoch 2/30
2109/2109 [==============================] - 1s 311us/step - loss: 2.0622 - acc: 0.2176 - val_loss: 2.0262 - val_acc: 0.2133
Epoch 3/30
2109/2109 [==============================] - 1s 304us/step - loss: 1.8343 - acc: 0.3310 - val_loss: 1.8154 - val_acc: 0.3923
Epoch 4/30
2109/2109 [==============================] - 1s 290us/step - loss: 1.6292 - acc: 0.4116 - val_loss: 1.7554 - val_acc: 0.4265
Epoch 5/30
2109/2109 [==============================] - 1s 296us/step - loss: 1.4431 - acc: 0.5111 - val_loss: 1.7139 - val_acc: 0.4917
Epoch 6/30
2109/2109 [==============================] - 1s 322us/step - loss: 1.2412 - acc: 0.5941 - val_loss: 1.6673 - val_acc: 0.5182
Epoch 7/30
2109/2109 [==============================] - 1s 302us/step - loss: 1.1076 - acc: 0.6415 - val_loss: 1.6790 - val_acc: 0.5249
Epo

In [57]:
X_test[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [60]:
predict

array([14,  3, 14,  8, 14, 11,  6,  3, 14, 11, 11, 16, 11, 16,  6, 14, 14,
        6, 14,  6,  6,  1,  1, 15, 17, 13, 14,  3, 11, 11, 16,  3, 15,  6,
        1,  6, 16, 15,  6,  3, 14, 18, 14, 14, 14,  6, 15,  6, 16, 14, 15,
       11,  3, 14, 11, 14, 11,  3, 14,  6, 11,  1,  6, 17, 15, 14, 14,  1,
        3, 14, 14, 11, 14,  3, 14,  3, 17,  3, 13,  1, 16, 11,  3, 14, 14,
       11, 11,  3,  1,  1,  6,  9, 15, 15,  6, 11, 11, 11, 14, 15,  3, 14,
       13, 15,  8, 15,  3, 14, 14, 11,  3, 16, 16, 16, 14, 15,  3, 13,  3,
        3, 14, 11,  9, 16,  6, 15,  3, 15,  3,  3, 15,  1,  8, 14, 16,  1,
       11,  3, 15, 16, 18, 16,  3,  3,  3, 14, 14,  3, 17,  1,  3, 14, 17,
       11, 11,  6,  6, 13,  1, 16, 15,  6,  9, 17,  9, 15, 13,  6,  6, 11,
       14,  3, 15,  1, 16, 15,  6, 11,  3, 11,  6, 14, 11, 15,  3, 17, 11,
        3,  6, 15, 11,  6, 14,  6, 11, 14, 14,  3, 18, 11,  9, 15,  6,  3,
        6, 16, 14,  3, 17, 15,  8, 14, 11, 14, 14, 14,  8, 11,  3,  3, 14,
       15, 15,  6,  6, 18

In [61]:
y_test

array([14,  9, 14,  8, 14, 11,  6,  3, 14, 11, 11, 16, 11, 16, 14, 14, 14,
       14, 14,  6, 11, 17, 11, 15, 17, 11, 14,  3, 11, 11,  1,  3, 17,  6,
       11,  6,  3, 15, 14,  6, 14, 16, 14, 14,  6,  6, 15, 14, 11, 14, 11,
       11, 11, 14, 11, 14, 14, 14, 14,  6, 11,  6,  6,  3, 11,  8, 11,  3,
       11, 14, 11, 15, 14, 14, 14,  3, 15,  3,  3, 13, 15, 11,  3, 14, 14,
       11, 11,  3,  1,  1, 14, 16, 15, 15, 14, 11, 15,  6, 14, 15,  6, 14,
       11, 15, 10,  1,  3, 14,  3, 16,  3, 16, 16, 11,  8,  1,  3, 14,  3,
        6, 14, 11,  9,  6,  6, 11,  3,  6,  3,  3, 15,  1,  8, 14,  3, 14,
       13,  3, 11,  1, 11, 16, 15, 18,  3,  8, 14,  9, 14, 18,  3, 14, 11,
       14, 15, 16,  6,  6,  8, 14, 15, 11, 16,  8,  1, 15,  6,  6,  6, 11,
       11,  3, 11,  1, 11, 15,  6, 14, 17, 17,  6,  6, 11, 15,  3, 17, 11,
        3,  6, 15, 15,  6, 14,  6, 11, 14, 14,  3, 17, 11, 14, 15, 14,  3,
       14, 16,  6,  3, 17, 15, 11,  6, 11,  8, 14,  6,  8, 11,  3,  3, 14,
       11, 15,  6,  6,  3

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predict)

0.569060773480663

In [35]:
data_1['Kelas'].value_counts()

11    649
14    576
3     457
6     382
15    313
1     201
16    163
17     90
8      57
13     32
2      32
9      22
18     21
10     17
4       2
5       1
Name: Kelas, dtype: int64

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predict)

array([[ 20,   0,   6,   3,   0,   2,   0,  13,   2,   3,   8,   3,   0,
          0],
       [  0,   4,   1,   0,   1,   1,   0,   0,   0,   1,   0,   1,   0,
          1],
       [  2,   0,  85,  13,   4,   0,   0,   5,   2,   5,   8,  11,   1,
          1],
       [  2,   1,  16,  69,   0,   0,   0,   6,   2,  14,   3,   2,   0,
          0],
       [  1,   1,   0,   0,   8,   1,   0,   0,   1,   4,   0,   0,   1,
          0],
       [  0,   0,   3,   0,   1,   3,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   2,   1,   0,   0,   0,   1,   0,   1,   0,   0,
          0],
       [  9,   0,   8,  13,   1,   1,   0, 106,  10,  10,  27,   4,   4,
          2],
       [  4,   0,   1,   0,   0,   0,   0,   1,   2,   0,   2,   0,   0,
          0],
       [  2,   0,   7,  16,   2,   7,   0,  11,   2, 120,   0,   3,   2,
          1],
       [  4,   0,  10,   1,   0,   0,   0,  10,   1,   0,  60,   4,   4,
          0],
       [  1,   1,   9,   3,   0,   2,   0, 

In [65]:
#confusion matrix
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(np.unique(y_test)))
    plt.xticks(tick_marks, np.unique(y_test), rotation=45)
    plt.yticks(tick_marks, np.unique(y_test))
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')


# Compute confusion matrix
cm = confusion_matrix(y_test, predict)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.figure()
plot_confusion_matrix(cm)

# Normalize the confusion matrix by row (i.e by the number of samples
# in each class)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)
plt.figure()
plot_confusion_matrix(cm_normalized, title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[ 20   0   6   3   0   2   0  13   2   3   8   3   0   0]
 [  0   4   1   0   1   1   0   0   0   1   0   1   0   1]
 [  2   0  85  13   4   0   0   5   2   5   8  11   1   1]
 [  2   1  16  69   0   0   0   6   2  14   3   2   0   0]
 [  1   1   0   0   8   1   0   0   1   4   0   0   1   0]
 [  0   0   3   0   1   3   0   0   0   0   0   0   0   0]
 [  0   0   0   2   1   0   0   0   1   0   1   0   0   0]
 [  9   0   8  13   1   1   0 106  10  10  27   4   4   2]
 [  4   0   1   0   0   0   0   1   2   0   2   0   0   0]
 [  2   0   7  16   2   7   0  11   2 120   0   3   2   1]
 [  4   0  10   1   0   0   0  10   1   0  60   4   4   0]
 [  1   1   9   3   0   2   0   3   0   1   0  26   0   3]
 [  2   0   2   1   2   0   0   5   0   0   2   0  12   1]
 [  1   0   1   1   0   0   0   1   0   0   1   1   0   0]]
Normalized confusion matrix
[[0.33 0.   0.1  0.05 0.   0.03 0.   0.22 0.03 0.05 0.13 0.05 0.   0.  ]
 [0.   0.4  0.1  0.   0.1  0.1  

<Figure size 640x480 with 2 Axes>

<Figure size 640x480 with 2 Axes>

In [66]:
print(np.unique(y_test))

[ 1  2  3  6  8  9 10 11 13 14 15 16 17 18]
