In [2]:
import numpy as np
import pandas
from tensorflow import keras
from keras.models import Sequential
from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import Dense, Activation, Dropout
from sklearn.model_selection import StratifiedKFold

Using TensorFlow backend.


In [3]:
#masukin data1
data1=pandas.read_csv('D:\\SKRIPSI\\data\\data\\data pakai\\data_herbs(!5).csv', sep=',', header=None)
#masukin data2
data2=pandas.read_csv('D:\\SKRIPSI\\data\\data\\data pakai\\data_class(!5).csv', sep=',', header=None)

In [4]:
X = data1
y = data2
z = pandas.read_csv('D:\\SKRIPSI\\data\\data\\data pakai\\class(!5).csv', sep=',', header=None)

In [6]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=0)
for train_index, test_index in sss.split(X,z):
    X_train,X_test = X.iloc[train_index,:],X.iloc[test_index,:]
    y_train,y_test = y.iloc[train_index,:],y.iloc[test_index,:]
    model = Sequential()
    model.add(Dense(input_dim=X_train.shape[1], units=463,
                     kernel_initializer='normal', bias_initializer='zeros'))
    model.add(Activation('relu'))

    for i in range(0, 6):
        model.add(Dense(units=463, kernel_initializer='normal',
                         bias_initializer='zeros'))
        model.add(Activation('relu'))
        model.add(Dropout(.4))

    model.add(Dense(units=18))
    model.add(Activation('softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])
    model.fit(X_train, y_train,batch_size=24,epochs=30,verbose=1,validation_data=(X_test, y_test))
    score = model.evaluate(X_test, y_test, verbose=1)
    predict = model.predict_classes(X_test)

Train on 2109 samples, validate on 905 samples
Epoch 1/30
2109/2109 [==============================] - 5s 2ms/step - loss: 0.1723 - binary_accuracy: 0.9453 - val_loss: 0.1547 - val_binary_accuracy: 0.9491
Epoch 2/30
2109/2109 [==============================] - 4s 2ms/step - loss: 0.1421 - binary_accuracy: 0.9531 - val_loss: 0.1392 - val_binary_accuracy: 0.9537
Epoch 3/30
2109/2109 [==============================] - 4s 2ms/step - loss: 0.1215 - binary_accuracy: 0.9587 - val_loss: 0.1322 - val_binary_accuracy: 0.9577
Epoch 4/30
2109/2109 [==============================] - 4s 2ms/step - loss: 0.1075 - binary_accuracy: 0.9651 - val_loss: 0.1254 - val_binary_accuracy: 0.9619
Epoch 5/30
2109/2109 [==============================] - 4s 2ms/step - loss: 0.0958 - binary_accuracy: 0.9689 - val_loss: 0.1387 - val_binary_accuracy: 0.9617
Epoch 6/30
2109/2109 [==============================] - 4s 2ms/step - loss: 0.0848 - binary_accuracy: 0.9729 - val_loss: 0.1413 - val_binary_accuracy: 0.9596
Epoch

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predict)

ValueError: Classification metrics can't handle a mix of multilabel-indicator and multiclass targets

In [57]:
X_test[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [60]:
predict

array([14,  3, 14,  8, 14, 11,  6,  3, 14, 11, 11, 16, 11, 16,  6, 14, 14,
        6, 14,  6,  6,  1,  1, 15, 17, 13, 14,  3, 11, 11, 16,  3, 15,  6,
        1,  6, 16, 15,  6,  3, 14, 18, 14, 14, 14,  6, 15,  6, 16, 14, 15,
       11,  3, 14, 11, 14, 11,  3, 14,  6, 11,  1,  6, 17, 15, 14, 14,  1,
        3, 14, 14, 11, 14,  3, 14,  3, 17,  3, 13,  1, 16, 11,  3, 14, 14,
       11, 11,  3,  1,  1,  6,  9, 15, 15,  6, 11, 11, 11, 14, 15,  3, 14,
       13, 15,  8, 15,  3, 14, 14, 11,  3, 16, 16, 16, 14, 15,  3, 13,  3,
        3, 14, 11,  9, 16,  6, 15,  3, 15,  3,  3, 15,  1,  8, 14, 16,  1,
       11,  3, 15, 16, 18, 16,  3,  3,  3, 14, 14,  3, 17,  1,  3, 14, 17,
       11, 11,  6,  6, 13,  1, 16, 15,  6,  9, 17,  9, 15, 13,  6,  6, 11,
       14,  3, 15,  1, 16, 15,  6, 11,  3, 11,  6, 14, 11, 15,  3, 17, 11,
        3,  6, 15, 11,  6, 14,  6, 11, 14, 14,  3, 18, 11,  9, 15,  6,  3,
        6, 16, 14,  3, 17, 15,  8, 14, 11, 14, 14, 14,  8, 11,  3,  3, 14,
       15, 15,  6,  6, 18

In [61]:
y_test

array([14,  9, 14,  8, 14, 11,  6,  3, 14, 11, 11, 16, 11, 16, 14, 14, 14,
       14, 14,  6, 11, 17, 11, 15, 17, 11, 14,  3, 11, 11,  1,  3, 17,  6,
       11,  6,  3, 15, 14,  6, 14, 16, 14, 14,  6,  6, 15, 14, 11, 14, 11,
       11, 11, 14, 11, 14, 14, 14, 14,  6, 11,  6,  6,  3, 11,  8, 11,  3,
       11, 14, 11, 15, 14, 14, 14,  3, 15,  3,  3, 13, 15, 11,  3, 14, 14,
       11, 11,  3,  1,  1, 14, 16, 15, 15, 14, 11, 15,  6, 14, 15,  6, 14,
       11, 15, 10,  1,  3, 14,  3, 16,  3, 16, 16, 11,  8,  1,  3, 14,  3,
        6, 14, 11,  9,  6,  6, 11,  3,  6,  3,  3, 15,  1,  8, 14,  3, 14,
       13,  3, 11,  1, 11, 16, 15, 18,  3,  8, 14,  9, 14, 18,  3, 14, 11,
       14, 15, 16,  6,  6,  8, 14, 15, 11, 16,  8,  1, 15,  6,  6,  6, 11,
       11,  3, 11,  1, 11, 15,  6, 14, 17, 17,  6,  6, 11, 15,  3, 17, 11,
        3,  6, 15, 15,  6, 14,  6, 11, 14, 14,  3, 17, 11, 14, 15, 14,  3,
       14, 16,  6,  3, 17, 15, 11,  6, 11,  8, 14,  6,  8, 11,  3,  3, 14,
       11, 15,  6,  6,  3

0.569060773480663

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predict)

array([[ 20,   0,   6,   3,   0,   2,   0,  13,   2,   3,   8,   3,   0,
          0],
       [  0,   4,   1,   0,   1,   1,   0,   0,   0,   1,   0,   1,   0,
          1],
       [  2,   0,  85,  13,   4,   0,   0,   5,   2,   5,   8,  11,   1,
          1],
       [  2,   1,  16,  69,   0,   0,   0,   6,   2,  14,   3,   2,   0,
          0],
       [  1,   1,   0,   0,   8,   1,   0,   0,   1,   4,   0,   0,   1,
          0],
       [  0,   0,   3,   0,   1,   3,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   2,   1,   0,   0,   0,   1,   0,   1,   0,   0,
          0],
       [  9,   0,   8,  13,   1,   1,   0, 106,  10,  10,  27,   4,   4,
          2],
       [  4,   0,   1,   0,   0,   0,   0,   1,   2,   0,   2,   0,   0,
          0],
       [  2,   0,   7,  16,   2,   7,   0,  11,   2, 120,   0,   3,   2,
          1],
       [  4,   0,  10,   1,   0,   0,   0,  10,   1,   0,  60,   4,   4,
          0],
       [  1,   1,   9,   3,   0,   2,   0, 

In [65]:
#confusion matrix
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(np.unique(y_test)))
    plt.xticks(tick_marks, np.unique(y_test), rotation=45)
    plt.yticks(tick_marks, np.unique(y_test))
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')


# Compute confusion matrix
cm = confusion_matrix(y_test, predict)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.figure()
plot_confusion_matrix(cm)

# Normalize the confusion matrix by row (i.e by the number of samples
# in each class)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)
plt.figure()
plot_confusion_matrix(cm_normalized, title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[ 20   0   6   3   0   2   0  13   2   3   8   3   0   0]
 [  0   4   1   0   1   1   0   0   0   1   0   1   0   1]
 [  2   0  85  13   4   0   0   5   2   5   8  11   1   1]
 [  2   1  16  69   0   0   0   6   2  14   3   2   0   0]
 [  1   1   0   0   8   1   0   0   1   4   0   0   1   0]
 [  0   0   3   0   1   3   0   0   0   0   0   0   0   0]
 [  0   0   0   2   1   0   0   0   1   0   1   0   0   0]
 [  9   0   8  13   1   1   0 106  10  10  27   4   4   2]
 [  4   0   1   0   0   0   0   1   2   0   2   0   0   0]
 [  2   0   7  16   2   7   0  11   2 120   0   3   2   1]
 [  4   0  10   1   0   0   0  10   1   0  60   4   4   0]
 [  1   1   9   3   0   2   0   3   0   1   0  26   0   3]
 [  2   0   2   1   2   0   0   5   0   0   2   0  12   1]
 [  1   0   1   1   0   0   0   1   0   0   1   1   0   0]]
Normalized confusion matrix
[[0.33 0.   0.1  0.05 0.   0.03 0.   0.22 0.03 0.05 0.13 0.05 0.   0.  ]
 [0.   0.4  0.1  0.   0.1  0.1  

<Figure size 640x480 with 2 Axes>

<Figure size 640x480 with 2 Axes>